captainVersion: 4
services:
  $$cap_appname:
    image: ghcr.io/cbx0-dev/anistream-api:latest
    volumes:
      - $$cap_appname-assets:/data/assets
    restart: unless-stopped
    environment:
      SIDECAR_PATH: /app/sidecar
      ASSETS_PATH: /data/assets
      DATABASE_MIGRATION_PATH: /app/migration
      DATABASE_DRIVER: $$cap_database_driver
      DATABASE_METADATA_CONNECTION_STRING: $$cap_metadata_connection_string
      DATABASE_PROFILE_CONNECTION_STRING: $$cap_profile_connection_string
    caproverExtra:
      containerHttpPort: '8080'

  $$cap_appname-worker:
    depends_on:
      - $$cap_appname
    image: ghcr.io/cbx0-dev/anistream-worker:latest
    volumes:
      - $$cap_appname-assets:/data/assets
    restart: unless-stopped
    environment:
      SIDECAR_PATH: /app/sidecar
      ASSETS_PATH: /data/assets
      DATABASE_MIGRATION_PATH: /app/migration
      DATABASE_DRIVER: $$cap_database_driver
      DATABASE_METADATA_CONNECTION_STRING: $$cap_metadata_connection_string
      DATABASE_PROFILE_CONNECTION_STRING: $$cap_profile_connection_string
    caproverExtra:
      notExposeAsWebApp: 'true'