name: Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  app_unittest:
    name: Test App (${{ matrix.target }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: ["standalone", "client"]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: 'app/package-lock.json'

      - name: Install dependencies
        run: |
          cd app
          npm ci

      - name: Run I18n generator
        run: node app/i18n.gen.cjs

      - name: Build
        run: |
          cd app
          export APPLICATION_TARGET="${{ matrix.target }}"
          npm run build

      - name: Run Unit tests
        run: |
          cd app
          export APPLICATION_TARGET="${{ matrix.target }}"
          npm test

  server_unittest:
    name: Test Server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup ASP.NET Core
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '9.0.x'

      - name: Build Solution
        run: dotnet build ./AniStream.slnx

      - name: Run Unit tests
        run: dotnet test ./AniStream.slnx --no-build